weights: ./weights/yolov5s.pt
cfg: ./models/yolov5s.yaml
data: ./data/lp.yaml
hyp: ./data/hyp.lp.yaml
epochs: 5
batch_size: 8
img_size:
- 960
- 960
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 4
saving_epoch: 20
project: runs/train
name: exp
exist_ok: false
total_batch_size: 8
world_size: 1
global_rank: -1
save_dir: runs/train/exp3
